# Generated by Django 3.0.3 on 2020-04-08 10:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(null=True)),
                ('datetimestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PUT', 'PUT'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('GET', 'GET')], default='GET', max_length=6)),
                ('input', jsonfield.fields.JSONField(null=True)),
                ('output', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(null=True)),
                ('datetimestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PUT', 'PUT'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('GET', 'GET')], default='GET', max_length=6)),
                ('input', jsonfield.fields.JSONField(null=True)),
                ('output', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSSParserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(null=True)),
                ('datetimestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PUT', 'PUT'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('GET', 'GET')], default='GET', max_length=6)),
                ('input', jsonfield.fields.JSONField(null=True)),
                ('output', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(null=True)),
                ('datetimestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PUT', 'PUT'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('GET', 'GET')], default='GET', max_length=6)),
                ('input', jsonfield.fields.JSONField(null=True)),
                ('output', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
