# Generated by Django 3.0.3 on 2020-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200409_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsstat',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsstat',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rssparserstat',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersstat',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
