# Generated by Django 3.0.3 on 2020-03-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200325_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='score_sign',
            new_name='direction',
        ),
    ]
