# Generated by Django 3.0.3 on 2020-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200325_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='direction',
            field=models.CharField(choices=[('UP', 'up'), ('DN', 'down')], default='UP', max_length=2),
        ),
    ]
