# Generated by Django 3.0.3 on 2020-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200325_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='direction',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], default='up', max_length=4),
        ),
    ]
