# Generated by Django 3.0.3 on 2020-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200325_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created', 'score'], 'verbose_name_plural': 'News'},
        ),
    ]
