# Generated by Django 3.0.3 on 2020-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default='Default name', max_length=64),
            preserve_default=False,
        ),
    ]
