# Generated by Django 3.0.3 on 2020-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentsToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSSParserToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatsToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
